version: "3"

services:
  olaindex:
    image: ghcr.io/apocalypsor/olaindex:latest
    container_name: olaindex
    ports:
      - 55880:80
      - 55443:443
    volumes:
      - ./env.conf:/OLAINDEX/.env
      - ./storage:/OLAINDEX/storage
    restart: unless-stopped


  redis:
    image: redis:alpine
    container_name: olaindex-redis
    restart: unless-stopped